steps:
# Copy the website content to a GS bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Sync the website content
  args: ['gsutil', '-m', 'rsync', '-d', '-r', '/site/', 'gs://bradley-cantrell.dev']